# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bhello.proto\x12\x05hello\".\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08greeting\x18\x02 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"E\n\x0c\x44\x65layedReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12$\n\x07request\x18\x02 \x03(\x0b\x32\x13.hello.HelloRequest2\xe3\x01\n\x05Hello\x12/\n\x05hello\x12\x13.hello.HelloRequest\x1a\x11.hello.HelloReply\x12\x37\n\x0bparrotHello\x12\x13.hello.HelloRequest\x1a\x11.hello.HelloReply0\x01\x12\x39\n\x0b\x63lientHello\x12\x13.hello.HelloRequest\x1a\x13.hello.DelayedReply(\x01\x12\x35\n\x07\x62iHello\x12\x13.hello.HelloRequest\x1a\x11.hello.HelloReply(\x01\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hello_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLOREQUEST._serialized_start=22
  _HELLOREQUEST._serialized_end=68
  _HELLOREPLY._serialized_start=70
  _HELLOREPLY._serialized_end=99
  _DELAYEDREPLY._serialized_start=101
  _DELAYEDREPLY._serialized_end=170
  _HELLO._serialized_start=173
  _HELLO._serialized_end=400
# @@protoc_insertion_point(module_scope)
